#ifndef USBD_DRIVER_H_
#define USBD_DRIVER_H_

#include "stm32f407xx.h"

#define USB_OTG_HS_GLOBAL   ((USB_OTG_GlobalTypeDef *)(USB_OTG_HS_PERIPH_BASE + USB_OTG_GLOBAL_BASE))
#define USB_OTG_HS_DEVICE   ((USB_OTG_DeviceTypeDef *)(USB_OTG_HS_PERIPH_BASE + USB_OTG_DEVICE_BASE))
#define USB_OTG_HS_PCGCCTL  ((uint32_t *)(USB_OTG_HS_PERIPH_BASE + USB_OTG_HS_PCGCCTL_PERIPH_BASE))

#define USB_OTG_FS_GLOBAL   ((USB_OTG_GlobalTypeDef *)(USB_OTG_FS_PERIPH_BASE + USB_OTG_GLOBAL_BASE))
#define USB_OTG_FS_DEVICE   ((USB_OTG_DeviceTypeDef *)(USB_OTG_FS_PERIPH_BASE + USB_OTG_DEVICE_BASE))
#define USB_OTG_FS_PCGCCTL  ((uint32_t *)(USB_OTG_FS_PERIPH_BASE + USB_OTG_FS_PCGCCTL_PERIPH_BASE))

void usbd_core_init();
void connect();
void disconnect();

#endif // !USBD_DRIVER_H_
